### PR TITLE
Add Matrix room

### PR DESCRIPTION
**Pull request by AtiusAmy**
I'm an Amygirl in an amy world

### CODE REVIEW

**Comment by heliguy4599** [comment]
Why remove the discord link? I want to point to both so people on either can join.

**Comment by AtiusAmy** [comment]
I did not remove it-

**Comment by heliguy4599** [comment]
My mistake I read the funky highlights wrong.

**Comment by heliguy4599** [comment]
My mistake I read the funky highlights wrong.

**Pull request merged**
